server:
  port: 6789
  tomcat:
    uri-encoding: UTF-8
    basedir: ${logging.path}/tomcat
    accesslog:
      enabled: true
      pattern: common
      directory: ${logging.path}/tomcat
    max-threads: 200
  servlet:
    context-path: /${spring.application.name}
  ssl:
    key-store: config/server.keystore
    key-alias: tomcat
    enabled: true
    key-store-password: 123456
    key-store-type: JKS
  session:
    # session过期时间，单位：秒
    timeout: 300
  title: 快付通商户侧管理平台
spring:
  application:
    name: kft-mcht-server
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    encoding: utf-8
    mode: LEGACYHTML5
    cache: false
  http:
    encoding:
      force: true
  mail:
    host: smtp.qq.com
    username: lai0755@vip.qq.com
    password: kdhsucrupxpobidf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    from: ${spring.mail.username}
    title: 登录验证码校验
    text: 本次登陆验证码为：%s。登录成功后该验证码自动失效！
logging:
  path: ${LOG_PATH:logs}
  file: ${spring.application.name}.log
  config: config/logback-spring.xml


#javamelody config
javamelody:
  init-parameters:
    log: false
    # to change the default storage directory:
    storage-directory: /tmp/javamelody_${spring.application.name}_${USER}
    # to change the default "/monitoring" path
    monitoring-path: /status/monitoring

mybatis:
    configLocation: /mybatis/mybatis-config.xml
    basePackage: com.mcoder.kft.mapper
    mapperLocations: classpath:mapper/*.xml

kft:
  keyStore:
    - merchantId: 2018112002636404
      type: PKCS12
      path: config/certs/2018112002636404/chengxiang.pfx
      password:
      keyPassword:
    - merchantId: 2019031902924240
      type: PKCS12
      path: config/certs/2019031902924240/gaoxinyuan-pri.pfx
      password:
      keyPassword:
  clientIp: 125.91.17.161
  language: zh_CN
  serviceVersion: 1.0.0-PRD
  http:
    domain: merchant.kftpay.com.cn
    port: 8443
    connectionTimeoutSeconds: 60
    responseTimeoutSeconds: 60
  sftp:
    accountName: 2018112002636404
    password: 636404
    domain: sftp.kftpay.com.cn
    port: 22222
    dir: /reconfiles
  product:
    trade: 1BB00DBF
    tradeQuery: 2GCA0AAF
    queryAvailableBalance: 2GCB0AAA
    queryBalanceChange: 2GCB0AAA
    sfptQuery: 2GCC0AAB
  errorCode:
    fail:
      - CUST_KFTBANK_00000039
    process:
      - CUST_CHANNEL_00009108
  files:
    balanceChangeFile: C:/kft/download/balance_change/%s
    sftpFile: C:/kft/download/sftp/%s.zip

druid:
  name: ${spring.application.name}
  username:
  password:
  url: jdbc:sqlite:config\kft-server.db
  initialSize: 10
  minIdle: 10
  maxActive: 50
  maxWait: 300000
  validationQuery: SELECT 'x'
  maxPoolPreparedStatementPerConnectionSize: 0
  removeAbandoned: true
  logAbandoned: true
  monitor:
    url: /status/druid/*

login:
  # 是否校验登陆邮箱验证码
  emailCheck: true
  pwdCheck: true
