server:
  port: 8443
  tomcat:
    uri-encoding: UTF-8
    basedir: ${logging.path}/tomcat
    accesslog:
      enabled: true
      pattern: common
      directory: ${logging.path}/tomcat
    max-threads: 200
  servlet:
    context-path: /${spring.application.name}
  ssl:
    key-store: classpath:server.keystore
    key-alias: tomcat
    enabled: true
    key-store-password: 123456
    key-store-type: JKS
  session:
    # session过期时间，单位：秒
    timeout: 3600
  title: 测试title
spring:
  application:
    name: kft-mcht-server
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    encoding: utf-8
    mode: LEGACYHTML5
    cache: false
  http:
    encoding:
      force: true
  mail:
    host: smtp.qq.com
    username: 1194688733@qq.com
    password: qfpwylpiystebaba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    from: ${spring.mail.username}
    title: 登录验证码校验
    text: 本次登陆验证码为：%s。登录成功后该验证码自动失效！
logging:
  path: ${LOG_PATH:logs}
  file: ${spring.application.name}.log
  config: classpath:logback-spring.xml


#javamelody config
javamelody:
  init-parameters:
    log: false
    # to change the default storage directory:
    storage-directory: /tmp/javamelody_${spring.application.name}_${USER}
    # to change the default "/monitoring" path
    monitoring-path: /status/monitoring

mybatis:
  configLocation: /mybatis/mybatis-config.xml
  basePackage: com.mcoder.kft.mapper
  mapperLocations: classpath:mapper/*.xml

kft:
  merchantInfoConf:
    - merchantId: 2018102500097289
      type: PKCS12
      path: D:\Program Files\Java\projects\musclecoder\kft-mcht-server\env\test\config\certs\2018102500097289\pfx.pfx
      password: 123456
      keyPassword: 123456
      product:
        trade: 2BA00BBA
        tradeQuery: 2GCA0AAH
        queryAvailableBalance: 2GCB0AAA
        queryBalanceChange: 2GCB0AAB
        sfptQuery: 2ACBDEFG
    - merchantId: 2019031902924240
      type: PKCS12
      path: D:\Program Files\Java\projects\musclecoder\kft-mcht-server\env\test\config\certs\2018102500097289\pfx.pfx
      password: 123456
      keyPassword: 123456
      product:
        trade: 2BA00BBA
        tradeQuery: 2GCA0AAH
        queryAvailableBalance: 2GCB0AAA
        queryBalanceChange: 2GCB0AAB
        sfptQuery: 2ACBDEFG
  clientIp: 10.36.160.37
  language: zh_CN
  serviceVersion: 1.0.0-IEST
  http:
    domain: 218.17.35.123
    port: 6443
    connectionTimeoutSeconds: 60
    responseTimeoutSeconds: 600
  sftp:
    accountName: 2018102500097289
    password: admin1234
    domain: 218.17.35.123
    port: 22
    dir: /reconfiles
  errorCode:
    fail:
      - CUST_KFTBANK_00000039
    process:
      - CUST_CHANNEL_00009108
  files:
    balanceChangeFile: d:/balance_change/%s.txt
    sftpFile: d:/sftp/%s.zip

druid:
  name: ${spring.application.name}
  username:
  password:
  url: jdbc:sqlite:D:\Program Files\Java\projects\musclecoder\kft-mcht-server\env\test\config\kft-server.db
  initialSize: 10
  minIdle: 10
  maxActive: 50
  maxWait: 300000
  validationQuery: SELECT 'x'
  maxPoolPreparedStatementPerConnectionSize: 0
  removeAbandoned: true
  logAbandoned: true
  monitor:
    url: /status/druid/*

login:
  emailCheck: false
  pwdCheck: false
